### ISSUE TITLE
About true posterior when N=100

### ISSUE THREAD

**Issue by 11510880** [mengxiangming/ep-demo#1]
Hi, 
I've tried your code and perhaps there is an small issue when N=100-- there is no true posterior appearing in the results when N=100 and methods='Gauss'

**Comment by mengxiangming** [comment]
Hi, thanks a lot for point out this issue. It is caused by numerical issues since in that case the density value tend to be zero. I have just fixed it by transforming to the log domain. Thanks again and please let me know if there is any further problems.
